server:
  port: 8443
  ssl:
    key-store: "classpath:server.p12"
    key-store-password: "password"
    key-store-type: PKCS12
    client-auth: want
    trust-store-type: jks
    trust-store: "classpath:rootCA.jks"
    trust-store-password: "password"


#security:
#  require-ssl: true


